name: check_database

services:
  db:
    image: mysql:8.0
    container_name: check_db
    environment:
      MYSQL_DATABASE: check_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD : password
    ports:
      - '3306:3306'
    volumes:
      - my-db-data:/var/lib/mysql
volumes:
  my-db-data:
